jobs:
  include:
    - language: go
      go: 1.13.x
      name: "deploy"
      script:
        - go run main.go
       deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

