jobs:
  include:
    - language: go
      go: 1.13.x
      name: "deploy"
      script:
        - go run main.go
        - go build -o automatic_disco main.go
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        draft: true
        file: "automatic_disco"
        on:
          tags: true


